### PR TITLE
Add a catch-all exception block to improve robustness

### PR DESCRIPTION
**Pull request by hgani**
One possible exception is NullPointerException when we pass a null value in custom targeting or in lat/long.

### CODE REVIEW

**Comment by jpriebe** [comment]
What happens in the Titanium app if you don't have this try/catch block in the module?

**Comment by hgani** [comment]
It crashes the app. 

Arguably we can explicitly check and filter out the null values before passing them to the module or we can use String.valueOf() instead toString() which is causing the crash, but this try/catch's main purpose is to serve as a safe guard for the unexpected, which can be quite severe because this generally affects multiple screens (all screens that show ads will crash).

**Comment by jpriebe** [comment]
Can you catch an exception up in the Javascript?  Or does it just crash immediately?  I'm assuming it's the latter.

It seems a little drastic to wrap the entire block in try/catch, which results in the adview not getting created when a single parameter is set to null.

Wouldn't most publishers prefer to show the adview even if they don't have the custom targeting values to pass to DFP?  I know we would.

I think it would be better to add some error checking to each of the various parameters.

I'm not sure where the null value became a problem.  Was it this line when you try to get the KrollDict:

 KrollDict ct = d.getKrollDict("customTargeting");

or this line when you try to call a method on the returned object?

 Log.d (TAG, "has " + ct.size () + " items in customTargeting dictionary:");

If it's the former, I'm not sure what you can do, other than wrap the whole customTargeting block in a try/catch.

If it's the latter, you could do something like

 if (ct != null)
 {
   //...
 }

I'd prefer to see some parameter sanitization, maybe in conjunction with a try/catch so that the adview can still be created.

**Comment by hgani** [comment]
@jpriebe Thanks for taking the time to understand the pull request ...

In response to your points:

- No, we can't catch the exception in JS because processProperties() gets executed on a different thread from the JS code.

- The NullPointerException gets thrown when the individual value inside custom targeting and location is null. There are some of the infringing lines:
    - b.putString (entry.getKey(), entry.getValue().toString ());
    - Log.d (TAG, "  - latitude:  " + ld.getDouble ("latitude").toString ());

- Good point, my pull request is unclear about what it's trying to protect against and it prevents the ad from getting served when one of the values is null. How about if I update the pull request to protect the specific lines that might throw NullPointerException, e.g by changing entry.getValue().toString() to String.valueOf(entry.getValue())

- As you suggested, this is going to be in conjunction to the try-catch that I've already put, because of the reason I mentioned earlier, which is to protect against the unexpected that could crash the entire app.

**Comment by jpriebe** [comment]
Sounds good to me.  I committed a bunch of changes yesterday (to fix app hangs in getAdvertisingId() and to improve the logging), so I think you've got conflicts that need to be resolved.

**Comment by hgani** [comment]
@jpriebe I've added the specific null checks (line 188 and 199). I've tested them thoroughly on my Titanium app.

Thanks

**Pull request merged**
